import React, { useState, useCallback, useEffect, useRef } from 'react';
import { View, Text, TouchableOpacity, ScrollView, SafeAreaView, StyleSheet, Modal, Platform, Dimensions, Animated, ActivityIndicator } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import * as Haptics from 'expo-haptics';
import { Audio } from 'expo-av';
import { COUNTRIES_CAPITALS } from './src/data/countries';
import { MOUNTAINS } from './src/data/mountains';
import { RIVERS } from './src/data/rivers';
import { LAKES } from './src/data/lakes';
import { LEVELS, CONTINENTS, CONTINENT_ICONS, DIFFICULTIES } from './src/data/levels';
import { shuffle, getLevel, getNextLevel, getLevelIndex, getDailySeed, seededRandom } from './src/utils/helpers';
import { genCapitalQ, genFlagQ, genMountainQ, genRiverQ, genLakeQ, Question } from './src/utils/questions';
import { loadGameState, saveValue } from './src/hooks/useStorage';

const QUIZ_LENGTH = 10;
const { width: SCREEN_WIDTH } = Dimensions.get('window');

// Sound effect files — these are loaded from assets/sounds/
// Each file is a short WAV generated by generate-sounds.js
const SOUND_FILES: Record<string, any> = {
  correct: require('./assets/sounds/correct.wav'),
  wrong: require('./assets/sounds/wrong.wav'),
  levelup: require('./assets/sounds/levelup.wav'),
  tap: require('./assets/sounds/tap.wav'),
};

// Play a sound effect. If it fails (e.g. on web or simulator), it silently skips.
// The sound is loaded, played, and then cleaned up from memory when finished.
const playSound = async (type: 'correct' | 'wrong' | 'levelup' | 'tap') => {
  try {
    const { sound } = await Audio.Sound.createAsync(SOUND_FILES[type]);
    await sound.playAsync();
    // Clean up: unload the sound from memory once it finishes playing
    sound.setOnPlaybackStatusUpdate((status: any) => {
      if (status.didJustFinish) sound.unloadAsync();
    });
  } catch {
    // Silently ignore — haptics still provide feedback even if sound fails
  }
};

export default function App() {
  const [screen, setScreen] = useState<'home' | 'quiz' | 'learn' | 'results' | 'levels'>('home');
  const [xp, setXp] = useState(0);
  const [streak, setStreak] = useState(0);
  const [bestStreak, setBestStreak] = useState(0);
  const [hearts, setHearts] = useState(5);
  const [totalCorrect, setTotalCorrect] = useState(0);
  const [totalAnswered, setTotalAnswered] = useState(0);
  const [selectedContinent, setSelectedContinent] = useState('All');
  const [difficulty, setDifficulty] = useState('easy');
  const [activeLesson, setActiveLesson] = useState('capitals');
  const [questions, setQuestions] = useState<(Question | null)[]>([]);
  const [currentQ, setCurrentQ] = useState(0);
  const [selected, setSelected] = useState<string | null>(null);
  const [showResult, setShowResult] = useState(false);
  const [isCorrect, setIsCorrect] = useState(false);
  const [sessionScore, setSessionScore] = useState(0);
  const [sessionCorrect, setSessionCorrect] = useState(0);
  const [comboCount, setComboCount] = useState(0);
  const [bestCombo, setBestCombo] = useState(0);
  const [learnedItems, setLearnedItems] = useState<string[]>([]);
  const [showLevelUp, setShowLevelUp] = useState(false);
  const [newLevel, setNewLevel] = useState<any>(null);
  const [dailyCompleted, setDailyCompleted] = useState(false);
  const [dailySeed] = useState(getDailySeed());
  const [learnCards, setLearnCards] = useState<any[]>([]);
  const [learnIdx, setLearnIdx] = useState(0);
  const [learnFlipped, setLearnFlipped] = useState(false);


  const [isLoading, setIsLoading] = useState(true);
  const fadeAnim = useRef(new Animated.Value(0)).current;
  const shakeAnim = useRef(new Animated.Value(0)).current;
  const scaleAnim = useRef(new Animated.Value(1)).current;
  const initialized = useRef(false);


  const xpMult = DIFFICULTIES[difficulty].xpMult;

  // Fade-in animation helper
  const fadeIn = useCallback(() => {
    fadeAnim.setValue(0);
    Animated.timing(fadeAnim, { toValue: 1, duration: 300, useNativeDriver: true }).start();
  }, [fadeAnim]);

  // Shake animation for wrong answers
  const triggerShake = useCallback(() => {
    Animated.sequence([
      Animated.timing(shakeAnim, { toValue: 10, duration: 50, useNativeDriver: true }),
      Animated.timing(shakeAnim, { toValue: -10, duration: 50, useNativeDriver: true }),
      Animated.timing(shakeAnim, { toValue: 10, duration: 50, useNativeDriver: true }),
      Animated.timing(shakeAnim, { toValue: 0, duration: 50, useNativeDriver: true }),
    ]).start();
  }, [shakeAnim]);

  // Pop animation for correct answers
  const triggerPop = useCallback(() => {
    Animated.sequence([
      Animated.timing(scaleAnim, { toValue: 1.15, duration: 120, useNativeDriver: true }),
      Animated.timing(scaleAnim, { toValue: 1, duration: 120, useNativeDriver: true }),
    ]).start();
  }, [scaleAnim]);

  // Load saved state
  useEffect(() => {
    loadGameState().then(s => {
      setXp(s.xp);
      setStreak(s.streak);
      setBestStreak(s.bestStreak);
      setTotalCorrect(s.totalCorrect);
      setTotalAnswered(s.totalAnswered);
      setLearnedItems(s.learnedItems);
      const todaysSeed = getDailySeed();
      const isToday = s.dailyDate === todaysSeed;
      setDailyCompleted(isToday ? s.dailyCompleted : false);
      setDifficulty(s.difficulty);
      setSelectedContinent(s.selectedContinent);
      initialized.current = true;
      setIsLoading(false);
      fadeIn();
    });
  }, []);

  // Save state when values change (guarded: only after initial load to prevent overwriting saved data on startup)
  useEffect(() => { if (initialized.current) saveValue('XP', xp); }, [xp]);
  useEffect(() => { if (initialized.current) saveValue('STREAK', streak); }, [streak]);
  useEffect(() => { if (initialized.current) saveValue('BEST_STREAK', bestStreak); }, [bestStreak]);
  useEffect(() => { if (initialized.current) saveValue('TOTAL_CORRECT', totalCorrect); }, [totalCorrect]);
  useEffect(() => { if (initialized.current) saveValue('TOTAL_ANSWERED', totalAnswered); }, [totalAnswered]);
  useEffect(() => { if (initialized.current) saveValue('LEARNED_ITEMS', learnedItems); }, [learnedItems]);
  useEffect(() => { if (initialized.current) saveValue('DAILY_COMPLETED', dailyCompleted); }, [dailyCompleted]);
  useEffect(() => { if (initialized.current) saveValue('DIFFICULTY', difficulty); }, [difficulty]);
  useEffect(() => { if (initialized.current) saveValue('CONTINENT', selectedContinent); }, [selectedContinent]);

  const level = getLevel(xp);
  const nextLvl = getNextLevel(xp);
  const levelProgress = nextLvl ? ((xp - level.minXP) / (nextLvl.minXP - level.minXP)) * 100 : 100;
  const levelIdx = getLevelIndex(xp);

  const startQuiz = useCallback((lesson: string, continent: string, isDaily = false) => {
    let qs: (Question | null)[] = [];
    const usedIds = new Set<string>();
    const gen = (type: string) => {
      let q: Question | null = null;
      if (type === 'capitals') q = genCapitalQ(continent, usedIds, difficulty);
      else if (type === 'flags') q = genFlagQ(continent, usedIds, difficulty);
      else if (type === 'mountains') q = genMountainQ(continent, usedIds, difficulty);
      else if (type === 'rivers') q = genRiverQ(continent, usedIds, difficulty);
      else if (type === 'lakes') q = genLakeQ(continent, usedIds, difficulty);
      if (q) usedIds.add(q.id);
      return q;
    };
    if (isDaily) {
      const rng = seededRandom(dailySeed);
      const lessons = ['capitals', 'flags', 'mountains', 'rivers', 'lakes'];
      for (let i = 0; i < QUIZ_LENGTH; i++) {
        const l = lessons[Math.floor(rng() * lessons.length)];
        qs.push(gen(l));
      }
    } else {
      for (let i = 0; i < QUIZ_LENGTH; i++) {
        qs.push(gen(lesson));
      }
    }
    setQuestions(qs);
    setCurrentQ(0);
    setSelected(null);
    setShowResult(false);
    setSessionScore(0);
    setSessionCorrect(0);
    setComboCount(0);
    setBestCombo(0);
    setHearts(5);

    setActiveLesson(isDaily ? 'daily' : lesson);
    setScreen('quiz');
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    fadeIn();
  }, [difficulty, dailySeed]);

  const startLearn = useCallback((lesson: string, continent: string) => {
    let cards: any[] = [];
    const filterCont = (arr: any[]) => continent === 'All' ? arr : arr.filter((x: any) => x.continent === continent);
    if (lesson === 'capitals') {
      cards = shuffle(filterCont(COUNTRIES_CAPITALS)).slice(0, 20).map(c => ({
        id: c.country, front: `${c.flag} ${c.country}`, back: c.capital, detail: `Continent: ${c.continent}`
      }));
    } else if (lesson === 'mountains') {
      const pool = filterCont(MOUNTAINS).length >= 4 ? filterCont(MOUNTAINS) : MOUNTAINS;
      cards = shuffle(pool).slice(0, 20).map(m => ({
        id: m.name, front: m.name, back: `${m.height}\n${m.range}`, detail: m.fact
      }));
    } else if (lesson === 'rivers') {
      const pool = filterCont(RIVERS).length >= 4 ? filterCont(RIVERS) : RIVERS;
      cards = shuffle(pool).slice(0, 20).map(r => ({
        id: r.name, front: r.name, back: `${r.length}\n${r.country}`, detail: r.fact
      }));
    } else if (lesson === 'flags') {
      cards = shuffle(filterCont(COUNTRIES_CAPITALS)).slice(0, 20).map(c => ({
        id: c.country, front: c.flag, back: c.country, detail: `Continent: ${c.continent}`
      }));
    } else if (lesson === 'lakes') {
      const pool = filterCont(LAKES).length >= 4 ? filterCont(LAKES) : LAKES;
      cards = shuffle(pool).slice(0, 20).map(l => ({
        id: l.name, front: l.name, back: `${l.area}\n${l.country}`, detail: l.fact
      }));
    }
    setLearnCards(cards);
    setLearnIdx(0);
    setLearnFlipped(false);
    setScreen('learn');
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    fadeIn();
  }, []);

  const handleAnswer = (answer: string) => {
    if (showResult) return;
    const q = questions[currentQ];
    if (!q) return;
    const correct = answer === q.answer;
    setSelected(answer);
    setShowResult(true);
    setIsCorrect(correct);
    setTotalAnswered(p => p + 1);
    if (correct) {
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      playSound('correct');
      triggerPop();
      const combo = comboCount + 1;
      setComboCount(combo);
      setBestCombo(b => Math.max(b, combo));
      setTotalCorrect(p => p + 1);
      setSessionCorrect(p => p + 1);
      const base = 10 + (combo >= 3 ? combo * 3 : 0) + (combo >= 5 ? 5 : 0);
      const gained = Math.round(base * xpMult);
      setSessionScore(p => p + gained);
      const oldIdx = getLevelIndex(xp);
      setXp(p => {
        const n = p + gained;
        if (getLevelIndex(n) > oldIdx) {
          setTimeout(() => {
            setNewLevel(getLevel(n));
            setShowLevelUp(true);
            Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
            playSound('levelup');
          }, 600);
        }
        return n;
      });
      setStreak(p => { const ns = p + 1; setBestStreak(b => Math.max(b, ns)); return ns; });
    } else {
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
      playSound('wrong');
      triggerShake();
      setComboCount(0);
      setStreak(0);
      setHearts(p => p - 1);
    }
  };

  const nextQuestion = () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    if (hearts <= 0 || currentQ >= QUIZ_LENGTH - 1) {
      if (activeLesson === 'daily') {
        setDailyCompleted(true);
        saveValue('DAILY_DATE', getDailySeed());
      }
      setScreen('results');
      fadeIn();
      return;
    }
    setCurrentQ(p => p + 1);
    setSelected(null);
    setShowResult(false);

    fadeIn();
  };

  // ═══ LEVEL UP MODAL ═══
  const LevelUpModal = () => (
    <Modal visible={showLevelUp && !!newLevel} transparent animationType="fade">
      <View style={styles.modalOverlay}>
        <View style={styles.modalContent}>
          <Text style={[styles.modalLabel, { color: newLevel?.color }]}>LEVEL UP!</Text>
          <Text style={styles.modalIcon}>{newLevel?.icon}</Text>
          <Text style={styles.modalName}>{newLevel?.name}</Text>
          <Text style={styles.modalDesc}>{newLevel?.desc}</Text>
          <View style={[styles.badgeRow, { backgroundColor: (newLevel?.color || '#000') + '22' }]}>
            <Text style={[styles.badgeText, { color: newLevel?.color }]}>{newLevel?.badge} Badge Unlocked</Text>
          </View>
          <TouchableOpacity style={styles.modalBtn} onPress={() => setShowLevelUp(false)}>
            <Text style={styles.modalBtnText}>Continue</Text>
          </TouchableOpacity>
        </View>
      </View>
    </Modal>
  );

  // ═══ LOADING ═══
  if (isLoading) {
    return (
      <SafeAreaView style={[styles.container, { alignItems: 'center', justifyContent: 'center' }]}>
        <StatusBar style="dark" />
        <Text style={{ fontSize: 48, marginBottom: 12 }}>🌍</Text>
        <Text style={{ fontSize: 24, fontWeight: '800', color: '#22943F' }}>GeoQuest</Text>
        <ActivityIndicator size="large" color="#22943F" style={{ marginTop: 20 }} />
      </SafeAreaView>
    );
  }

  // ═══ LEARN MODE ═══
  if (screen === 'learn') {
    const card = learnCards[learnIdx];
    if (!card) { setScreen('home'); return null; }
    return (
      <SafeAreaView style={styles.container}>
        <StatusBar style="dark" />
        <View style={styles.topBar}>
          <TouchableOpacity onPress={() => setScreen('home')}><Text style={styles.backBtn}>{'<'}</Text></TouchableOpacity>
          <Text style={styles.topBarTitle}>Learn {learnIdx + 1}/{learnCards.length}</Text>
          <View style={{ width: 50 }} />
        </View>
        <View style={styles.progressBarBg}>
          <View style={[styles.progressBarFill, { width: `${((learnIdx + 1) / learnCards.length) * 100}%` as any, backgroundColor: '#34C759' }]} />
        </View>
        <ScrollView contentContainerStyle={{ padding: 20, alignItems: 'center' }}>
          <TouchableOpacity
            style={[styles.learnCard, learnFlipped ? styles.learnCardFlipped : null]}
            onPress={() => { setLearnFlipped(!learnFlipped); Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); }}
            activeOpacity={0.8}
          >
            {!learnFlipped ? (
              <>
                <Text style={styles.learnLabel}>QUESTION</Text>
                <Text style={styles.learnFront}>{card.front}</Text>
                <Text style={styles.tapHint}>Tap to reveal</Text>
              </>
            ) : (
              <>
                <Text style={[styles.learnLabel, { color: 'rgba(255,255,255,0.8)' }]}>ANSWER</Text>
                <Text style={[styles.learnFront, { color: 'white' }]}>{card.back}</Text>
                <Text style={[styles.learnDetail, { color: 'rgba(255,255,255,0.85)' }]}>{card.detail}</Text>
              </>
            )}
          </TouchableOpacity>
          <View style={styles.learnBtns}>
            <TouchableOpacity
              style={[styles.learnNavBtn, { opacity: learnIdx === 0 ? 0.4 : 1 }]}
              disabled={learnIdx === 0}
              onPress={() => { setLearnIdx(p => p - 1); setLearnFlipped(false); }}
            >
              <Text style={styles.learnNavBtnText}>Back</Text>
            </TouchableOpacity>
            {learnIdx < learnCards.length - 1 ? (
              <TouchableOpacity
                style={[styles.learnNavBtn, { backgroundColor: '#22943F' }]}
                onPress={() => {
                  setLearnIdx(p => p + 1);
                  setLearnFlipped(false);
                  if (!learnedItems.includes(card.id)) setLearnedItems(prev => [...prev, card.id]);
                }}
              >
                <Text style={[styles.learnNavBtnText, { color: 'white' }]}>Next</Text>
              </TouchableOpacity>
            ) : (
              <TouchableOpacity
                style={[styles.learnNavBtn, { backgroundColor: '#007AFF' }]}
                onPress={() => {
                  if (!learnedItems.includes(card.id)) setLearnedItems(prev => [...prev, card.id]);
                  setScreen('home');
                }}
              >
                <Text style={[styles.learnNavBtnText, { color: 'white' }]}>Done</Text>
              </TouchableOpacity>
            )}
          </View>
        </ScrollView>
      </SafeAreaView>
    );
  }

  // ═══ LEVELS ROADMAP ═══
  if (screen === 'levels') {
    return (
      <SafeAreaView style={styles.container}>
        <StatusBar style="dark" />
        <View style={styles.topBar}>
          <TouchableOpacity onPress={() => setScreen('home')}><Text style={styles.backBtn}>{'<'}</Text></TouchableOpacity>
          <Text style={styles.topBarTitle}>Level Roadmap</Text>
          <View style={{ width: 50 }} />
        </View>
        <ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 40 }}>
          <View style={[styles.levelHeader, { backgroundColor: level.color + '22' }]}>
            <Text style={{ fontSize: 64 }}>{level.icon}</Text>
            <Text style={styles.levelHeaderName}>{level.name}</Text>
            <Text style={[styles.levelHeaderXP, { color: level.color }]}>{xp} XP</Text>
            {nextLvl && <Text style={styles.levelHeaderNext}>{nextLvl.minXP - xp} XP to {nextLvl.name}</Text>}
          </View>
          {LEVELS.map((l, i) => {
            const unlocked = xp >= l.minXP;
            const isCurrent = i === levelIdx;
            return (
              <View key={i}>
                {i > 0 && (
                  <View style={{ alignItems: 'center' }}>
                    <View style={{ width: 3, height: 24, backgroundColor: unlocked ? l.color : '#E5E5EA' }} />
                  </View>
                )}
                <View style={[
                  styles.levelRow,
                  { borderColor: isCurrent ? l.color : '#E5E5EA', backgroundColor: isCurrent ? l.color + '15' : 'white', opacity: unlocked ? 1 : 0.5 }
                ]}>
                  <Text style={{ fontSize: 36 }}>{l.icon}</Text>
                  <View style={{ flex: 1 }}>
                    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                      <Text style={{ fontSize: 16, fontWeight: '800', color: unlocked ? '#1C1C1E' : '#8E8E93' }}>{l.name}</Text>
                      {isCurrent && (
                        <View style={[styles.currentBadge, { backgroundColor: l.color }]}>
                          <Text style={styles.currentBadgeText}>CURRENT</Text>
                        </View>
                      )}
                    </View>
                    <Text style={{ fontSize: 12, color: '#8E8E93' }}>{l.minXP} XP</Text>
                  </View>
                  {unlocked && <Text style={{ fontSize: 18 }}>{'✅'}</Text>}
                </View>
              </View>
            );
          })}
        </ScrollView>
      </SafeAreaView>
    );
  }

  // ═══ HOME ═══
  if (screen === 'home') {
    return (
      <SafeAreaView style={styles.container}>
        <StatusBar style="light" />
        <View style={styles.topBar}>
          <Text style={styles.appTitle}>GeoQuest</Text>
          <View style={{ flexDirection: 'row', gap: 12 }}>
            <Text style={styles.statText}>🔥 {streak}</Text>
            <Text style={styles.statText}>{xp} XP</Text>
          </View>
        </View>

        {/* Hero Banner */}
        <View style={styles.heroBanner}>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 14 }}>
            <TouchableOpacity onPress={() => setScreen('levels')} style={styles.heroIcon}>
              <Text style={{ fontSize: 44 }}>{level.icon}</Text>
            </TouchableOpacity>
            <View style={{ flex: 1 }}>
              <Text style={styles.heroTitle}>{level.name}</Text>
              <Text style={styles.heroSub}>{learnedItems.length} items learned</Text>
              <View style={styles.heroProgressBg}>
                <View style={[styles.heroProgressFill, { width: `${levelProgress}%` as any }]} />
              </View>
              <Text style={styles.heroNextLvl}>{nextLvl ? `${nextLvl.minXP - xp} XP to ${nextLvl.name}` : 'Max level!'}</Text>
            </View>
          </View>
        </View>

        <ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 100 }}>
          {/* Stats Row */}
          <View style={styles.statsRow}>
            {[
              { l: 'Best Streak', v: `🔥 ${bestStreak}` },
              { l: 'Accuracy', v: totalAnswered > 0 ? `${Math.round((totalCorrect / totalAnswered) * 100)}%` : '—' },
              { l: 'Learned', v: `${learnedItems.length}` }
            ].map((s, i) => (
              <View key={i} style={styles.statCard}>
                <Text style={styles.statCardValue}>{s.v}</Text>
                <Text style={styles.statCardLabel}>{s.l}</Text>
              </View>
            ))}
          </View>

          {/* Daily Challenge */}
          <TouchableOpacity
            style={[styles.card, { flexDirection: 'row', alignItems: 'center', gap: 14, opacity: dailyCompleted ? 0.6 : 1 }]}
            onPress={() => !dailyCompleted && startQuiz('capitals', 'All', true)}
            disabled={dailyCompleted}
          >
            <Text style={{ fontSize: 36 }}>{dailyCompleted ? '✅' : '📅'}</Text>
            <View style={{ flex: 1 }}>
              <Text style={styles.cardTitle}>Daily Challenge</Text>
              <Text style={styles.cardSub}>{dailyCompleted ? 'Completed today!' : 'Mixed quiz - New every day'}</Text>
            </View>
            {!dailyCompleted && <Text style={{ fontSize: 14, fontWeight: '700', color: '#FF9500' }}>Play</Text>}
          </TouchableOpacity>

          {/* Difficulty */}
          <View style={styles.card}>
            <Text style={styles.sectionTitle}>Difficulty</Text>
            <View style={{ flexDirection: 'row', gap: 8 }}>
              {Object.entries(DIFFICULTIES).map(([key, d]) => (
                <TouchableOpacity
                  key={key}
                  style={[styles.diffBtn, { borderColor: difficulty === key ? '#007AFF' : '#E5E5EA', backgroundColor: difficulty === key ? '#E8F0FE' : 'white' }]}
                  onPress={() => setDifficulty(key)}
                >
                  <Text style={{ fontSize: 22 }}>{d.icon}</Text>
                  <Text style={[styles.diffLabel, { color: difficulty === key ? '#007AFF' : '#1C1C1E' }]}>{d.label}</Text>
                  <Text style={styles.diffDetail}>{`${d.choices} choices`}</Text>
                  <Text style={styles.diffXP}>{d.xpMult}x XP</Text>
                </TouchableOpacity>
              ))}
            </View>
          </View>

          {/* Region */}
          <View style={styles.card}>
            <Text style={styles.sectionTitle}>Region</Text>
            <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 7 }}>
              {CONTINENTS.map(c => (
                <TouchableOpacity
                  key={c}
                  style={[styles.regionBtn, {
                    borderColor: selectedContinent === c ? '#007AFF' : '#E5E5EA',
                    backgroundColor: selectedContinent === c ? '#E8F0FE' : 'white'
                  }]}
                  onPress={() => setSelectedContinent(c)}
                >
                  <Text style={{ fontSize: 13, fontWeight: '600', color: selectedContinent === c ? '#007AFF' : '#1C1C1E' }}>
                    {CONTINENT_ICONS[c]} {c}
                  </Text>
                </TouchableOpacity>
              ))}
            </View>
          </View>

          {/* Lessons */}
          <View style={[styles.card, { padding: 0, overflow: 'hidden' }]}>
            <View style={{ padding: 14, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: '#F2F2F7' }}>
              <Text style={styles.sectionTitle}>Lessons</Text>
            </View>
            {[
              { id: 'capitals', icon: '🏛️', title: 'Capital Cities', desc: `${COUNTRIES_CAPITALS.length} countries to master` },
              { id: 'flags', icon: '🏁', title: 'Flags', desc: `${COUNTRIES_CAPITALS.length} flags to identify` },
              { id: 'mountains', icon: '⛰️', title: 'Mountains', desc: `${MOUNTAINS.length} peaks to conquer` },
              { id: 'rivers', icon: '🌊', title: 'Rivers', desc: `${RIVERS.length} rivers to explore` },
              { id: 'lakes', icon: '💧', title: 'Lakes', desc: `${LAKES.length} lakes to discover` },
            ].map((lesson, i, arr) => (
              <View key={lesson.id} style={{ borderBottomWidth: i < arr.length - 1 ? 1 : 0, borderBottomColor: '#F2F2F7' }}>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12, padding: 12, paddingHorizontal: 18 }}>
                  <View style={styles.lessonIcon}><Text style={{ fontSize: 26 }}>{lesson.icon}</Text></View>
                  <View style={{ flex: 1 }}>
                    <Text style={{ fontSize: 15, fontWeight: '700', color: '#1C1C1E' }}>{lesson.title}</Text>
                    <Text style={{ fontSize: 12, color: '#8E8E93' }}>{lesson.desc}</Text>
                  </View>
                </View>
                <View style={{ flexDirection: 'row', gap: 8, paddingHorizontal: 18, paddingBottom: 12, marginLeft: 56 }}>
                  <TouchableOpacity style={styles.learnBtn} onPress={() => startLearn(lesson.id, selectedContinent)}>
                    <Text style={styles.learnBtnText}>Learn</Text>
                  </TouchableOpacity>
                  <TouchableOpacity style={styles.quizBtn} onPress={() => startQuiz(lesson.id, selectedContinent)}>
                    <Text style={styles.quizBtnText}>Quiz</Text>
                  </TouchableOpacity>
                </View>
              </View>
            ))}
          </View>
        </ScrollView>
        <LevelUpModal />
      </SafeAreaView>
    );
  }

  // ═══ QUIZ ═══
  if (screen === 'quiz') {
    const q = questions[currentQ];
    if (!q) return null;
    const progress = ((currentQ + (showResult ? 1 : 0)) / QUIZ_LENGTH) * 100;
    const catColors: Record<string, string> = { capitals: '#22943F', flags: '#E91E63', mountains: '#FF9500', rivers: '#007AFF', lakes: '#00BCD4', daily: '#AF52DE' };
    const catColor = catColors[activeLesson] || '#22943F';

    return (
      <SafeAreaView style={styles.container}>
        <StatusBar style="dark" />
        {/* Quiz Header */}
        <View style={styles.quizHeader}>
          <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}>
            <TouchableOpacity onPress={() => setScreen('home')}><Text style={{ fontSize: 22 }}>{'✕'}</Text></TouchableOpacity>
            <View style={{ flexDirection: 'row', gap: 3 }}>
              {Array.from({ length: 5 }, (_, i) => (
                <Text key={i} style={{ fontSize: 18, opacity: i < hearts ? 1 : 0.2 }}>{'❤️'}</Text>
              ))}
            </View>
            <Text style={{ fontSize: 14, fontWeight: '700', color: catColor }}>{sessionScore} XP</Text>
          </View>
          <View style={styles.progressBarBg}>
            <View style={[styles.progressBarFill, { width: `${progress}%` as any, backgroundColor: catColor }]} />
          </View>
          <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginTop: 5 }}>
            <Text style={styles.quizMeta}>{currentQ + 1}/{QUIZ_LENGTH}</Text>
            {comboCount >= 2 && <Text style={{ fontSize: 11, fontWeight: '700', color: '#FF9500' }}>🔥 {comboCount}x Combo</Text>}
            <Text style={styles.quizMeta}>{DIFFICULTIES[difficulty].label}</Text>
          </View>
        </View>

        <Animated.ScrollView contentContainerStyle={{ padding: 20 }} style={{ opacity: fadeAnim }}>
          {/* Question */}
          <Animated.View style={{ alignItems: 'center', marginBottom: 20, transform: [{ translateX: shakeAnim }, { scale: scaleAnim }] }}>
            <Text style={{ fontSize: 20, fontWeight: '800', color: '#1C1C1E', textAlign: 'center', lineHeight: 28 }}>{q.question}</Text>
          </Animated.View>

          {/* Multiple Choice */}
          <View style={{ gap: 8 }}>
              {q.options.map((opt, i) => {
                const isSel = selected === opt;
                const isAnswer = opt === q.answer;
                let bg = 'white', borderColor = '#E5E5EA', textColor = '#1C1C1E';
                if (showResult && isAnswer) { bg = '#E8F8EE'; borderColor = '#34C759'; textColor = '#1B7A3D'; }
                else if (showResult && isSel && !isAnswer) { bg = '#FFF0F0'; borderColor = '#FF3B30'; textColor = '#CC0000'; }
                else if (isSel) { bg = '#E8F0FE'; borderColor = '#007AFF'; textColor = '#007AFF'; }

                return (
                  <TouchableOpacity
                    key={`${currentQ}-${i}`}
                    style={[styles.optBtn, { backgroundColor: bg, borderColor }]}
                    onPress={() => handleAnswer(opt)}
                    disabled={showResult}
                  >
                    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
                      <View style={[styles.optIndex, {
                        backgroundColor: showResult && isAnswer ? '#34C759' : showResult && isSel ? '#FF3B30' : '#F2F2F7'
                      }]}>
                        <Text style={{ color: showResult && (isAnswer || isSel) ? 'white' : '#1C1C1E', fontSize: 14, fontWeight: '800' }}>
                          {showResult && isAnswer ? '✓' : showResult && isSel ? '✕' : String.fromCharCode(65 + i)}
                        </Text>
                      </View>
                      <Text style={{ fontSize: 15, fontWeight: '600', color: textColor, flex: 1 }}>{opt}</Text>
                    </View>
                  </TouchableOpacity>
                );
              })}
            </View>
        </Animated.ScrollView>

        {/* Result Footer */}
        {showResult && (
          <View style={[styles.resultFooter, { backgroundColor: isCorrect ? '#E8F8EE' : '#FFF0F0', borderTopColor: isCorrect ? '#34C759' : '#FF3B30' }]}>
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 4 }}>
              <Text style={{ fontSize: 24 }}>{isCorrect ? '🎉' : '😔'}</Text>
              <View>
                <Text style={{ fontSize: 16, fontWeight: '800', color: isCorrect ? '#1B7A3D' : '#CC0000' }}>
                  {isCorrect ? 'Correct!' : 'Wrong!'}
                </Text>
                {!isCorrect && <Text style={{ fontSize: 13, color: '#666' }}>Answer: {q.answer}</Text>}
              </View>
            </View>
            <Text style={{ fontSize: 12, color: isCorrect ? '#1B7A3D' : '#8E8E93', marginBottom: 10 }}>{q.fact}</Text>
            <TouchableOpacity
              style={[styles.continueBtn, { backgroundColor: isCorrect ? '#34C759' : '#FF3B30' }]}
              onPress={nextQuestion}
            >
              <Text style={styles.continueBtnText}>
                {hearts <= 0 ? 'See Results' : currentQ >= QUIZ_LENGTH - 1 ? 'Finish!' : 'Continue'}
              </Text>
            </TouchableOpacity>
          </View>
        )}
        <LevelUpModal />
      </SafeAreaView>
    );
  }

  // ═══ RESULTS ═══
  if (screen === 'results') {
    const pct = Math.round((sessionCorrect / QUIZ_LENGTH) * 100);
    const stars = pct >= 90 ? 3 : pct >= 60 ? 2 : pct >= 30 ? 1 : 0;
    const catLabels: Record<string, string> = { capitals: 'Capitals', flags: 'Flags', mountains: 'Mountains', rivers: 'Rivers', lakes: 'Lakes', daily: 'Daily' };

    return (
      <SafeAreaView style={styles.container}>
        <StatusBar style="light" />
        <View style={[styles.resultsBanner, { backgroundColor: pct >= 60 ? '#22943F' : '#CC0000' }]}>
          <Text style={styles.resultsCatLabel}>{catLabels[activeLesson] || 'Quiz'} Complete</Text>
          <Text style={{ fontSize: 52, marginTop: 6 }}>{pct >= 80 ? '🏆' : pct >= 60 ? '🎉' : pct >= 30 ? '💪' : '📚'}</Text>
          <Text style={styles.resultsTitle}>
            {hearts <= 0 ? 'Out of Hearts!' : pct >= 80 ? 'Amazing!' : pct >= 60 ? 'Great Job!' : pct >= 30 ? 'Good Try!' : 'Keep Learning!'}
          </Text>
          <Text style={styles.resultsStars}>
            {Array.from({ length: 3 }, (_, i) => i < stars ? '⭐' : '☆').join(' ')}
          </Text>
        </View>
        <ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 100 }}>
          <View style={[styles.card, { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: level.color + '11' }]}>
            <Text style={{ fontSize: 36 }}>{level.icon}</Text>
            <View style={{ flex: 1 }}>
              <Text style={{ fontSize: 11, fontWeight: '700', color: '#8E8E93', textTransform: 'uppercase' }}>{level.name}</Text>
            </View>
            <Text style={{ fontSize: 18, fontWeight: '800', color: level.color }}>{xp} XP</Text>
          </View>
          <View style={styles.resultsGrid}>
            {[
              { i: '✅', l: 'Correct', v: `${sessionCorrect}/${QUIZ_LENGTH}` },
              { i: '⚡', l: 'XP Earned', v: `${sessionScore}` },
              { i: '🔥', l: 'Best Combo', v: `${bestCombo}x` },
              { i: '📊', l: 'Accuracy', v: `${pct}%` }
            ].map((s, idx) => (
              <View key={idx} style={styles.resultStatCard}>
                <Text style={{ fontSize: 24 }}>{s.i}</Text>
                <Text style={styles.resultStatValue}>{s.v}</Text>
                <Text style={styles.resultStatLabel}>{s.l}</Text>
              </View>
            ))}
          </View>
          <View style={{ gap: 10, marginTop: 16 }}>
            <TouchableOpacity style={styles.playAgainBtn} onPress={() => startQuiz(activeLesson === 'daily' ? 'capitals' : activeLesson, selectedContinent)}>
              <Text style={styles.playAgainBtnText}>Play Again</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.homeBtn} onPress={() => setScreen('home')}>
              <Text style={styles.homeBtnText}>Home</Text>
            </TouchableOpacity>
          </View>
        </ScrollView>
        <LevelUpModal />
      </SafeAreaView>
    );
  }

  return null;
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F2F2F7' },
  topBar: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingHorizontal: 16, paddingVertical: 14, backgroundColor: 'white',
    borderBottomWidth: 1, borderBottomColor: '#E5E5EA',
  },
  appTitle: { fontSize: 15, fontWeight: '800', color: '#1C1C1E' },
  statText: { fontSize: 14, fontWeight: '600', color: '#1C1C1E' },
  backBtn: { fontSize: 22, color: '#007AFF', fontWeight: '600' },
  topBarTitle: { fontSize: 17, fontWeight: '700', color: '#1C1C1E' },

  heroBanner: { backgroundColor: '#22943F', paddingHorizontal: 20, paddingBottom: 20, paddingTop: 8 },
  heroIcon: {
    width: 56, height: 56, borderRadius: 16, backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center', justifyContent: 'center',
  },
  heroTitle: { fontSize: 22, fontWeight: '800', color: 'white' },
  heroSub: { fontSize: 12, color: 'rgba(255,255,255,0.9)' },
  heroProgressBg: { backgroundColor: 'rgba(255,255,255,0.3)', borderRadius: 100, height: 7, marginTop: 6 },
  heroProgressFill: { height: '100%', backgroundColor: 'white', borderRadius: 100 },
  heroNextLvl: { fontSize: 11, color: 'rgba(255,255,255,0.75)', marginTop: 3 },

  statsRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  statCard: {
    flex: 1, backgroundColor: 'white', borderRadius: 16, padding: 12, alignItems: 'center',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 3 },
      android: { elevation: 2 },
    }),
  },
  statCardValue: { fontSize: 20, fontWeight: '800', color: '#1C1C1E' },
  statCardLabel: { fontSize: 10, color: '#8E8E93', fontWeight: '700', textTransform: 'uppercase' },

  card: {
    backgroundColor: 'white', borderRadius: 16, padding: 18, marginBottom: 12,
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 3 },
      android: { elevation: 2 },
    }),
  },
  cardTitle: { fontSize: 16, fontWeight: '800', color: '#1C1C1E' },
  cardSub: { fontSize: 12, color: '#8E8E93' },
  sectionTitle: { fontSize: 12, fontWeight: '700', color: '#8E8E93', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 10 },

  diffBtn: { flex: 1, padding: 10, borderRadius: 12, borderWidth: 2, alignItems: 'center' },
  diffLabel: { fontSize: 12, fontWeight: '700', marginTop: 2 },
  diffDetail: { fontSize: 10, color: '#8E8E93' },
  diffXP: { fontSize: 10, color: '#FF9500', fontWeight: '700' },

  regionBtn: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 100, borderWidth: 2 },

  lessonIcon: {
    width: 44, height: 44, borderRadius: 12, backgroundColor: '#F2F2F7',
    alignItems: 'center', justifyContent: 'center',
  },
  learnBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 10, borderWidth: 2, borderColor: '#007AFF' },
  learnBtnText: { fontSize: 13, fontWeight: '700', color: '#007AFF' },
  quizBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 10, backgroundColor: '#007AFF' },
  quizBtnText: { fontSize: 13, fontWeight: '700', color: 'white' },

  progressBarBg: { backgroundColor: '#E5E5EA', borderRadius: 100, height: 8, marginHorizontal: 16, marginTop: 8, overflow: 'hidden' },
  progressBarFill: { height: '100%', borderRadius: 100 },

  quizHeader: { backgroundColor: 'white', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#E5E5EA' },
  quizMeta: { fontSize: 11, color: '#8E8E93', fontWeight: '600' },
  optBtn: { padding: 14, borderRadius: 14, borderWidth: 2.5 },
  optIndex: { width: 26, height: 26, borderRadius: 7, alignItems: 'center', justifyContent: 'center' },

  resultFooter: { padding: 16, paddingBottom: 24, borderTopWidth: 3 },
  continueBtn: { padding: 16, borderRadius: 14, alignItems: 'center' },
  continueBtnText: { color: 'white', fontSize: 16, fontWeight: '700' },

  resultsBanner: { paddingVertical: 40, paddingHorizontal: 20, alignItems: 'center' },
  resultsCatLabel: { fontSize: 13, fontWeight: '700', color: 'rgba(255,255,255,0.85)', textTransform: 'uppercase', letterSpacing: 2 },
  resultsTitle: { fontSize: 26, fontWeight: '900', color: 'white', marginTop: 6 },
  resultsStars: { fontSize: 48, letterSpacing: 6, marginTop: 4 },
  resultsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  resultStatCard: {
    width: (SCREEN_WIDTH - 50) / 2, backgroundColor: 'white', borderRadius: 16, padding: 14, alignItems: 'center',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 3 },
      android: { elevation: 2 },
    }),
  },
  resultStatValue: { fontSize: 20, fontWeight: '800', color: '#1C1C1E', marginTop: 2 },
  resultStatLabel: { fontSize: 10, color: '#8E8E93', fontWeight: '600', textTransform: 'uppercase' },
  playAgainBtn: { backgroundColor: '#22943F', padding: 16, borderRadius: 14, alignItems: 'center' },
  playAgainBtnText: { color: 'white', fontSize: 16, fontWeight: '700' },
  homeBtn: { backgroundColor: '#F2F2F7', padding: 16, borderRadius: 14, alignItems: 'center' },
  homeBtnText: { color: '#1C1C1E', fontSize: 16, fontWeight: '700' },

  learnCard: {
    width: '100%', minHeight: 260, borderRadius: 20, padding: 32, backgroundColor: 'white',
    alignItems: 'center', justifyContent: 'center',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 20 },
      android: { elevation: 4 },
    }),
  },
  learnCardFlipped: { backgroundColor: '#34C759' },
  learnLabel: { fontSize: 14, fontWeight: '700', color: '#8E8E93', textTransform: 'uppercase', letterSpacing: 1 },
  learnFront: { fontSize: 32, fontWeight: '800', lineHeight: 42, textAlign: 'center', marginTop: 8 },
  learnDetail: { fontSize: 14, fontStyle: 'italic', marginTop: 16, textAlign: 'center' },
  tapHint: { fontSize: 13, color: '#8E8E93', marginTop: 20 },
  learnBtns: { flexDirection: 'row', gap: 12, marginTop: 28, width: '100%' },
  learnNavBtn: { flex: 1, padding: 14, borderRadius: 14, backgroundColor: '#E5E5EA', alignItems: 'center' },
  learnNavBtnText: { fontSize: 15, fontWeight: '700', color: '#1C1C1E' },

  levelHeader: { borderRadius: 20, padding: 24, alignItems: 'center', marginBottom: 20 },
  levelHeaderName: { fontSize: 26, fontWeight: '900', color: '#1C1C1E', marginTop: 6 },
  levelHeaderXP: { fontSize: 20, fontWeight: '800', marginTop: 4 },
  levelHeaderNext: { fontSize: 13, color: '#8E8E93', marginTop: 6 },
  levelRow: {
    flexDirection: 'row', alignItems: 'center', gap: 12, padding: 12, paddingHorizontal: 16,
    borderRadius: 14, borderWidth: 2,
  },
  currentBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 100 },
  currentBadgeText: { fontSize: 10, fontWeight: '700', color: 'white' },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.65)', alignItems: 'center', justifyContent: 'center' },
  modalContent: { backgroundColor: 'white', borderRadius: 28, padding: 36, width: '85%', alignItems: 'center' },
  modalLabel: { fontSize: 14, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 2 },
  modalIcon: { fontSize: 80, marginVertical: 4 },
  modalName: { fontSize: 34, fontWeight: '900', color: '#1C1C1E' },
  modalDesc: { fontSize: 15, color: '#8E8E93', marginTop: 6, fontStyle: 'italic', textAlign: 'center' },
  badgeRow: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 100, marginTop: 12 },
  badgeText: { fontSize: 14, fontWeight: '700' },
  modalBtn: { backgroundColor: '#22943F', padding: 16, borderRadius: 14, width: '100%', alignItems: 'center', marginTop: 20 },
  modalBtnText: { color: 'white', fontSize: 16, fontWeight: '700' },
});
